### PR TITLE
fix dead link to FAQ

### PR DESCRIPTION
**Pull request by stragu**
Signed-off-by: Stéphane Guillou <stephane.guillou@member.fsf.org>

Note that the FAQ doesn't give a MathJax vs KaTeX explanation just yet.
Some reasons for the switch are here: https://github.com/hedgedoc/react-client/issues/495

### Component/Part

Client changelog

### Description

Correct a dead link.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)

None

### CODE REVIEW

**Review by ErikMichelson — APPROVED** [review]

**Review by mrdrogdrog — APPROVED** [review]

**Comment by ErikMichelson** [comment]
There was an FAQ entry somewhere but never published. I guess it got away as we moved the FAQ page from the webpage to the docs.
This old commit still contains the text: https://github.com/hedgedoc/hedgedoc.github.io/blob/2d1dcb2f/content/english/faq.md

**Comment by mrdrogdrog** [comment]
The plan was to publish this entry as soon as we go live with 2.0 to prevent confusion. 
We could link the GitHub issue/pr instead.

**Comment by DerMolly** [comment]
I think linking the issue would be better for the time being anyway, since it's technical documentation.

**Comment by mrdrogdrog** [comment]
@ErikMichelson

**Comment by mrdrogdrog** [comment]
Well okay. @stragu can you change the link again, please?

**Comment by stragu** [comment]
Done. But as you can see, I am very bad at properly amending a commit: tried to squash it into a single commit, ended up with 3 instead. :sweat_smile:

**Comment by mrdrogdrog** [comment]
I would like to fix ist (otherwise we can't merge it) but you haven't activated "maintainers can edit my fork" when you created the PR :/

**Comment by mrdrogdrog** [comment]
Okay you can fix it by doing these steps:

1. Go into the directory
2. Run `git rebase HEAD~1`
3. This will create a conflict. Edit CHANGELOG.md and remove the conflicting lines but keep the correct one. Make sure to delete the git conflict markers.
4. Run `git add CHANGELOG.md`
5. Run `git rebase --continue`
6. Run `git rebase --signoff HEAD~1` to sign off existing commits
7. Run `git push --force-with-lease`

This should fix it.

**Comment by stragu** [comment]
I was having an issue at step 5, so used `git rebase HEAD~2` instead to catch more.
I end up with these two, signed off.
Hopefully that's OK? Thank you so much for your patience, @mrdrogdrog !

**Comment by mrdrogdrog** [comment]
Thanks @stragu :heart:

**Pull request merged**
