### PR TITLE
Add symlink for LICENSE

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
Repository License

### Description
This PR adds a symlink to the main license that is used in the repo.

### Steps

- [x] Added / updated documentation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### CODE REVIEW

**Review by DerMolly — APPROVED** [review]

**Comment by DerMolly** [comment]
Is it a good idea to add a symlink? Not all OS support those, do they?

**Review by ErikMichelson — APPROVED** [review]

**Comment by ErikMichelson** [comment]
Which OS doesn't support symlinks nowadays? Even MS Windows seems to support them.

**Comment by DerMolly** [comment]
Do they? Did not know that, then let's do it?

**Comment by ErikMichelson** [comment]
https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

Published December 2016

**Comment by mrdrogdrog** [comment]
Even Windows 7 supports symlinks. Even Windows Vista. Not sure about xp. But iirc symlinks have been introduced with NTFS.

anyway. This symlink is just for GitHub.

**Pull request merged**
