### PR TITLE
Optimize renovate config

### PR DESCRIPTION
**Pull request by mrdrogdrog**
### Component/Part
Renovate

### Description
This PR changes the renovate config:
- change version range strategy from "always pin" to "autodetect pin" by removing the config extension as the auto detection is already covered by `config:base`. (see https://docs.renovatebot.com/configuration-options/#rangestrategy).
- Remove `dependencyDashboard` as it is already covered by `config:base`

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### CODE REVIEW

**Comment by ErikMichelson** [comment]
I'm not sure whether the `auto` setting is the best way to handle dependencies.
Didn't we want to ensure that every dependency gets pinned? The auto strategy seems to only pin devDependencies and dependencies that are not a library.

**Comment by mrdrogdrog** [comment]
If i understand it correctly then it looks if current repository is a lib or an app.

Also: because we haven't set this value before the auto value has already been used before because this config is included in config:base.

**Comment by mrdrogdrog** [comment]
We could also drop the extra definition because it is already covered by config:base. But don't use "pin all dependencies" because this causes PRs like #1455

**Comment by ErikMichelson** [comment]
If there are sane defaults in `config:base` I see no reason for explicitly defining them again.

**Comment by mrdrogdrog** [comment]
I adjusted the content.

**Review by ErikMichelson — APPROVED** [review]

**Review by DerMolly — APPROVED** [review]

**Pull request merged**
