### PR TITLE
feat: add spell check

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
editor

### Description
This PR adds spell check.

### Steps

- [x] Added implementation
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
#479

### CODE REVIEW

**Comment by mrdrogdrog** [comment]
image

Doesn't look like it's working

**Comment by DerMolly** [comment]
grafik
Seems to be there are two places that this needs to be addeed…

**Comment by mrdrogdrog** [comment]
It seems like it's working.. but.. do we really want that? :sweat_smile:  The browser doesn't really know the context of many words. :/

image

**Comment by DerMolly** [comment]
> Maybe we should provide a method to turn on/off this functionality.

I think this would be the cleanest way of doing it for now. The typo.js and CM6 linter route is something we can always add later

**Comment by mrdrogdrog** [comment]
Then add it to the redux so we can turn it on/off as soon as we have a settings input.

**Comment by ErikMichelson** [comment]
> image
> 
> Doesn't look like it's working

For me its working neither (Chrome 103).

> Maybe we should provide a method to turn on/off this functionality.

Yes, that would be great for this.
 
> Or don't use the native OS typo system and build something with the codemirror linter plugin and typo.js

I think we should rather look whether it would be possible to ignore only specific lines from the browser's typo checker in a later iteration of this feature. Using native methods has the advantage of supporting external tools like LanguageTool as well as not being limited to a list of dictionaries we ship with HedgeDoc.

**Review by ErikMichelson — APPROVED** [review]

**Review by mrdrogdrog — APPROVED** [review]

**Pull request merged**
